var resources;
(function (resources) {
    var Resources = /** @class */ (function () {
        function Resources() {
        }
        Resources.Data = [
            {
                Sprites: [
                    { id: "forest", src: "./Assets/images/forest.png" },
                    { id: "sting", src: "./Assets/images/sting.png" },
                    { id: "archer", src: "./Assets/images/archer.png" },
                    { id: "arrow", src: "./Assets/images/arrow.png" },
                    { id: "bdrill0", src: "./Assets/images/0bee.png" },
                    { id: "bdrill1", src: "./Assets/images/1bee.png" },
                    { id: "bdrill2", src: "./Assets/images/2bee.png" },
                    { id: "bdrill3", src: "./Assets/images/3bee.png" },
                    { id: "bdrill4", src: "./Assets/images/4bee.png" },
                    { id: "bdrill5", src: "./Assets/images/5bee.png" },
                    { id: "bdrill6", src: "./Assets/images/6bee.png" },
                    { id: "bdrill7", src: "./Assets/images/7bee.png" },
                    { id: "bdrill8", src: "./Assets/images/8bee.png" },
                    { id: "bdrill9", src: "./Assets/images/9bee.png" },
                    { id: "bdrill10", src: "./Assets/images/10bee.png" },
                    { id: "bdrill11", src: "./Assets/images/11bee.png" },
                    { id: "bdrill12", src: "./Assets/images/12bee.png" },
                    { id: "bdrill13", src: "./Assets/images/13bee.png" },
                    { id: "bdrill14", src: "./Assets/images/14bee.png" },
                    { id: "bdrill15", src: "./Assets/images/15bee.png" },
                    { id: "bdrill16", src: "./Assets/images/16bee.png" },
                    { id: "bdrill17", src: "./Assets/images/17bee.png" },
                    { id: "bdrill18", src: "./Assets/images/18bee.png" },
                    { id: "bdrill19", src: "./Assets/images/19bee.png" },
                    { id: "bdrill20", src: "./Assets/images/20bee.png" },
                    { id: "bdrill21", src: "./Assets/images/21bee.png" },
                    { id: "bdrill22", src: "./Assets/images/22bee.png" },
                    { id: "bdrill23", src: "./Assets/images/23bee.png" },
                    { id: "bdrill24", src: "./Assets/images/24bee.png" },
                    { id: "bdrill25", src: "./Assets/images/25bee.png" },
                    { id: "bdrill26", src: "./Assets/images/26bee.png" },
                    { id: "bdrill27", src: "./Assets/images/27bee.png" },
                    { id: "bdrill28", src: "./Assets/images/28bee.png" },
                    { id: "bdrill29", src: "./Assets/images/29bee.png" },
                    { id: "mbdrill0", src: "./Assets/images/0mbee.png" },
                    { id: "mbdrill1", src: "./Assets/images/1mbee.png" },
                    { id: "mbdrill2", src: "./Assets/images/2mbee.png" },
                    { id: "mbdrill3", src: "./Assets/images/3mbee.png" },
                    { id: "mbdrill4", src: "./Assets/images/4mbee.png" },
                    { id: "mbdrill5", src: "./Assets/images/5mbee.png" },
                    { id: "mbdrill6", src: "./Assets/images/6mbee.png" },
                    { id: "mbdrill7", src: "./Assets/images/7mbee.png" },
                    { id: "mbdrill8", src: "./Assets/images/8mbee.png" },
                    { id: "mbdrill9", src: "./Assets/images/9mbee.png" },
                    { id: "mbdrill10", src: "./Assets/images/10mbee.png" },
                    { id: "mbdrill11", src: "./Assets/images/11mbee.png" },
                    { id: "mbdrill12", src: "./Assets/images/12mbee.png" },
                    { id: "mbdrill13", src: "./Assets/images/13mbee.png" },
                    { id: "mbdrill14", src: "./Assets/images/14mbee.png" },
                    { id: "mbdrill15", src: "./Assets/images/15mbee.png" },
                    { id: "mbdrill16", src: "./Assets/images/16mbee.png" },
                    { id: "mbdrill17", src: "./Assets/images/17mbee.png" },
                    { id: "mbdrill18", src: "./Assets/images/18mbee.png" },
                    { id: "mbdrill19", src: "./Assets/images/19mbee.png" },
                    { id: "mbdrill20", src: "./Assets/images/20mbee.png" },
                    { id: "mbdrill21", src: "./Assets/images/21mbee.png" },
                    { id: "mbdrill22", src: "./Assets/images/22mbee.png" },
                    { id: "mbdrill23", src: "./Assets/images/23mbee.png" },
                    { id: "mbdrill24", src: "./Assets/images/24mbee.png" },
                    { id: "mbdrill25", src: "./Assets/images/25mbee.png" },
                    { id: "mbdrill26", src: "./Assets/images/26mbee.png" },
                    { id: "mbdrill27", src: "./Assets/images/27mbee.png" },
                    { id: "mbdrill28", src: "./Assets/images/28mbee.png" },
                    { id: "mbdrill29", src: "./Assets/images/29mbee.png" },
                    { id: "healthBorder", src: "./Assets/images/healthBorder.png" },
                    { id: "greenFill", src: "./Assets/images/greenFill.png" },
                    { id: "redFill", src: "./Assets/images/redFill.png" },
                    { id: "goldenFill", src: "./Assets/images/goldenFill.png" },
                    { id: "amberNormal", src: "./Assets/images/amberNormal.png" },
                    { id: "amberDark", src: "./Assets/images/amberDark.png" },
                    { id: "rubyNormal", src: "./Assets/images/rubyNormal.png" },
                    { id: "rubyDark", src: "./Assets/images/rubyDark.png" },
                    { id: "logo", src: "./Assets/images/logo.png" },
                ],
                Sounds: [
                    { id: "buttonClick", src: "./Assets/audio/button.ogg" },
                    { id: "battle", src: "./Assets/audio/battle.ogg" },
                    { id: "over", src: "./Assets/audio/over.ogg" },
                    { id: "start", src: "./Assets/audio/start.ogg" },
                    { id: "arrowShoot", src: "./Assets/audio/arrow.ogg" },
                ]
            }
        ];
        return Resources;
    }());
    resources.Resources = Resources;
})(resources || (resources = {}));
//# sourceMappingURL=resources.js.map